# Generated by Django 2.2.3 on 2019-07-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombres')),
                ('nacionalidad', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
